export const siteCofig = {
	orgName: 'Debater',
	orgEmail: 'debater@life.com',
	siteUrl: process.env.SITE_URL || 'https://thedebater.co',
	icons: {},
	title: 'Debater - Open platform for debate and discussion',
	allLinks: [{}],
	keywords: [
		'Debate platform',
		'Online debates',
		'Community challenges',
		'Intellectual discourse',
		'Fun challenges',
		'Challenge communities',
		'Vibrant debates',
		'Eco-chambers discussion',
		'Broadcast topics',
		'Diverse perspectives',
		'Meme-based discussions',
		'Debate with memes',
		'Funny debates',
		'GIF-based debates',
		'Playful arguments',
		'Roundtable debate',
		'Live audio discussions',
		'Audio debate clubs',
		'Support, against, neutral debate',
		'Interactive comments',
		'Structured debates',
		'Reddit-style discussions',
		'Affirmative opinions',
		'Neutral perspectives',
		'Debate threads',
		'Follow topics',
		'Notifications for debates',
		'Like and dislike comments',
		'Community engagement',
		'Echo chambers',
		'Red pill vs blue pill',
		'Breaking echo chambers',
		'Diverse viewpoints',
		'Constructive discourse',
		'Debate app features',
		'Online discussion forum',
		'Thought-provoking topics',
		'Engaging debate community',
		'Debate and humor',
		'Debate app for memes',
		'Interactive debate platform',
		'Join debates online',
		'Real-time audio debates',
		'Engage in debates',
		'Chamber-based discussions',
		'Real-time discussions',
		'Debate with diverse views',
		'Debate social platform',
		'User-generated debates',
		'Live debate rooms',
		'Topic-based discussions',
		'Memes in debates',
		'Online voice debates',
		'Global debate community',
		'Express your opinion',
		'Debate with humor',
		'Structured discussion threads',
		'Online opinion sharing',
		'Voice-based debate rooms',
		'Debate participation',
		'Comment-based discussions',
		'Public debate platform',
		'Debate topics trending',
		'Debate with gifs and memes',
		'Cross-community debates',
		'Host your debates',
		'Live voice debates',
		'Dynamic debate topics',
		'Debate with reactions',
		'Democrats vs Republicans',
		'Liberals vs Conservatives',
		'Pro-choice vs Pro-life',
		'Environmentalists vs Climate Change Deniers',
		'Secularists vs Religious Fundamentalists',
		'Gun Control Advocates vs Gun Rights Advocates',
		'Feminists vs Anti-Feminists',
		'Atheists vs Theists',
		'LGBTQ+ Supporters vs Traditional Marriage Advocates',
		'Vegan vs Carnivores/Omnivores',
		'Capitalists vs Socialists',
		'Animal Rights Activists vs Animal Testing Advocates',
		'Flat Earth Believers vs Round Earth Advocates',
		'Anti-Vaxxers vs Pro-Vaccine Advocates',
		'Human Rights Activists vs Authoritarian Regimes',
		'Globalists vs Nationalists',
		'Science Advocates vs Science Skeptics',
		'Anti-Nuclear Power Activists vs Nuclear Power Advocates',
		'Labor Unions vs Corporatists',
		'Pro-Immigration vs Anti-Immigration',
		'Public Healthcare Advocates vs Private Healthcare Advocates',
		'Civil Libertarians vs Authoritarians',
		'Universal Basic Income (UBI) Supporters vs Welfare Critics',
		'Black Lives Matter Supporters vs All Lives Matter Advocates',
		'Pro-European Union vs Eurosceptics',
		'Renewable Energy Advocates vs Fossil Fuel Advocates',
		'Anti-Capital Punishment Advocates vs Pro-Capital Punishment Advocates',
		'Free Speech Advocates vs Censorship Advocates',
		'Digital Privacy Advocates vs Government Surveillance Supporters',
		'Progressive Taxation Advocates vs Flat Tax Advocates',
		'Pro-Union Advocates vs Right-to-Work Advocates',
		'Free Trade Supporters vs Protectionists',
		'Pro-Palestinian Activists vs Pro-Israel Activists',
		'Pacifists vs War Hawks',
		'Humanists vs Religious Traditionalists',
		'Anti-Establishment Activists vs Establishment Defenders',
		'Monarchists vs Republicans (anti-monarchy)',
		'Pro-Technology vs Luddites',
		'Body Positivity Advocates vs Body Shaming Advocates',
		'Organic Food Advocates vs GMOs Supporters',
		'Public Education Advocates vs Private Education Advocates',
		'Anti-GMO Activists vs Pro-GMO Advocates',
		'Anti-Fracking Activists vs Pro-Fracking Advocates',
		'Pro-Privacy Advocates vs Pro-Surveillance Advocates',
		'Environmental Conservationists vs Industrial Expansionists',
		'Anti-Colonialists vs Colonial Apologists',
		'Libertarians vs Statists',
		'Antifa (Anti-Fascists) vs Far-Right Extremists',
		'Pro-Internet Neutrality vs Anti-Internet Neutrality',
		'Pro-Drug Legalization vs Anti-Drug Legalization',
		'Reparations Advocates vs Anti-Reparations Advocates',
		'Climate Activists vs Climate Change Skeptics',
		'Anti-Imperialists vs Pro-Imperialists',
		'Techno-Optimists vs Techno-Skeptics',
		'Global Health Advocates vs Anti-Vaccine Movements',
		'Abolitionists (prison/police) vs Law and Order Advocates',
		'Multiculturalists vs Cultural Purists',
		'Privacy Advocates vs Pro-Government Surveillance',
		'Radical Environmentalists vs Pro-Development Advocates',
		'Advocates of Gender Neutral Language vs Traditional Language Advocates',
		'Egalitarians vs Hierarchical Traditionalists',
		'Pro-Indigenous Rights Activists vs Colonialism Defenders',
		'Social Justice Warriors vs Anti-SJW',
		'Anti-Fascists vs Neo-Nazis',
		'Inclusive Educators vs Traditional Educators',
		'Pro-Women’s Rights vs Anti-Women’s Rights Advocates',
		'Pro-Trans Rights vs Anti-Trans Rights Advocates',
		'Free Speech Absolutists vs Hate Speech Regulators',
		'Supporters of Universal Healthcare vs Private Healthcare Advocates',
		'Pro-Cannabis Legalization vs Anti-Cannabis Legalization',
		'Internet Freedom Advocates vs Censorship Supporters',
		'Antarctic Preservationists vs Pro-Antarctic Exploitation',
		'Anti-Racist Advocates vs Racial Supremacists',
		'Free Market Advocates vs Regulation Supporters',
		'Pro-Democracy Activists vs Dictatorship Supporters',
		'Cultural Relativists vs Moral Absolutists',
		'Animal Liberationists vs Animal Industry Supporters',
		'Zero Waste Advocates vs Disposable Culture Advocates',
		'Pro-Egalitarian Marriage vs Anti-Egalitarian Marriage',
		'Supporters of LGBTQ+ Rights vs Opponents of LGBTQ+ Rights',
		'Pro-Science Education vs Creationism Supporters',
		'Multilateralists vs Unilateralists',
		'Digital Rights Advocates vs Digital Monitoring Supporters',
		'Conservationists vs Resource Exploiters',
		'Anti-War Activists vs Pro-Military Interventionists',
		'Green Energy Supporters vs Coal Industry Advocates',
		'Rural Advocacy Groups vs Urban Advocacy Groups',
		'Migrant Rights Advocates vs Anti-Migrant Activists',
		'Pro-Consumer Protection vs Deregulation Advocates',
		'Pro-Civil Rights vs Opponents of Civil Rights',
		'Fair Trade Advocates vs Free Trade Advocates',
		'Anti-Zionists vs Zionists',
		'Direct Democracy Advocates vs Representative Democracy Advocates',
		'Pro-Social Programs vs Austerity Advocates',
		'Gender Equality Advocates vs Patriarchy Defenders',
		'Pro-Indigenous Land Rights vs Land Exploitation Advocates',
		'Humanitarian Interventionists vs Non-Interventionists',
		'Open Borders Advocates vs Border Security Advocates',
		'Digital Nomads vs Traditional Office Workers',
		'Anti-Corporate Activists vs Pro-Corporate Advocates',
	],
	description:
		'Dive into a wide range of intellectual and lively debates that challenge your views and engage you in meaningful discourse. Our platform offers users the chance to participate in or observe debates on controversial issues, ranging from political ideologies to social, environmental, and scientific topics. Whether you’re passionate about discussing Democrats vs. Republicans, exploring Pro-choice vs. Pro-life arguments, or analyzing Environmentalists vs. Climate Change Deniers, there’s a debate for everyone.',
	applicationName: 'Debater',
	publisher: 'Debater Admin',
	creator: 'Sagar rajak',
	openGraph: {
		title: 'Sagar rajak',
		url: '/',
	},
}

export type SiteConfig = typeof siteCofig
