export const siteCofig = {
	orgName: 'Debater',
	orgEmail: 'debater@life.com',
	siteUrl: process.env.SITE_URL || 'https://thedebater.co',
	icons: {},
	title: 'Debater - Open platform for debate and discussion',
	allLinks: [{}],
	keywords: [
		'Debate platform',
		'Online debates',
		'Community challenges',
		'Intellectual discourse',
		'Fun challenges',
		'Challenge communities',
		'Vibrant debates',
		'Eco-chambers discussion',
		'Broadcast topics',
		'Diverse perspectives',
		'Meme-based discussions',
		'Debate with memes',
		'Funny debates',
		'GIF-based debates',
		'Playful arguments',
		'Roundtable debate',
		'Live audio discussions',
		'Audio debate clubs',
		'Support, against, neutral debate',
		'Interactive comments',
		'Structured debates',
		'Reddit-style discussions',
		'Affirmative opinions',
		'Neutral perspectives',
		'Debate threads',
		'Follow topics',
		'Notifications for debates',
		'Like and dislike comments',
		'Community engagement',
		'Echo chambers',
		'Red pill vs blue pill',
		'Breaking echo chambers',
		'Diverse viewpoints',
		'Constructive discourse',
		'Debate app features',
		'Online discussion forum',
		'Thought-provoking topics',
		'Engaging debate community',
		'Debate and humor',
		'Debate app for memes',
		'Interactive debate platform',
	],
	description:
		'Dive into a wide range of intellectual and lively debates that challenge your views and engage you in meaningful discourse. Our platform offers users the chance to participate in or observe debates on controversial issues, ranging from political ideologies to social, environmental, and scientific topics.',
	applicationName: 'Debater',
	publisher: 'Debater Admin',
	creator: 'Sagar rajak',
	openGraph: {
		title: 'Sagar rajak',
		url: '/',
	},
}

export type SiteConfig = typeof siteCofig
